config/routes.rb
Rails.application.routes.draw do
  resources :spks
  resources :master_kapals
  root 'dashboard#index'  
  authenticated :user, ->(user) { user.admin? } do    
    get 'dashboard/pelabuhans'
    get 'dashboard/notices'
    get 'dashboard/comments'
    get 'dashboard/users'
    get 'dashboard/show_notice'
    get 'dashboard/routes'
  end
  get 'search', to: "search#index"
  get 'search/pelabuhan', to: "search#pelabuhan"
  get 'search/master_kapal', to: "search#master_kapal"
  resources :pelabuhans  
  devise_for :users, skip: [:sessions], controllers: {
    session: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session    
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'register', to: 'devise/registrations#new', as: :new_user_registration_c    
  end

  resources :notices do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")  
  # root "articles#index"  
end

app/models/notice.rb
class Notice < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :body
  has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  friendly_id :title, use: %i[slugged history finders]

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_user, except: %i[index show]

  # GET /notices or /notices.json
  def index
    @notices = Notice.includes(:user, :rich_text_body).all.order(created_at: :desc).page(params[:page]).per(5)
    add_breadcrumb('Pengumuman', nil, true)
  end

  # GET /notices/1 or /notices/1.json
  def show
    @comments = @notice.comments.includes(:user, :rich_text_body).order(created_at: :desc)

    mark_notifications_as_read
    add_breadcrumb('Pengumuman', notices_path, false)
    add_breadcrumb(@notice.title, nil, true)
  end

  # GET /notices/new
  def new
    @notice = Notice.new
    add_breadcrumb('Pengumuman', notices_path, false)
    add_breadcrumb('Tambah Pengumuman', nil, true)
  end

  # GET /notices/1/edit
  def edit
  end

  # notice /notices or /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.user = current_user    

    respond_to do |format|
      if @notice.save
        format.html { redirect_to notice_url(@notice), notice: "Notice was successfully created." }
        format.turbo_stream { render :create, locals: {notice: @notice} }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :new, status: :unprocessable_entity, locals: {notice: @notice} }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1 or /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to notice_url(@notice), notice: "Notice was successfully updated." }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1 or /notices/1.json
  def destroy
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url, notice: "Notice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def authorize_user
    notice = @notice || Notice
    authorize notice
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
      # If an old id or a numeric id was used to find the record, then
      # the request path will not match the notice_path, and we should do
      # a 301 redirect that uses the current friendly id.
      redirect_to @notice, :status => :moved_permanently if params[:id] != @notice.slug       
    end
    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:title, :body, :user_id)
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @notice.notifications_as_notice.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end      
    end

end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= turbo_frame_tag "new_notice" do %>
  <%= form_with(model: notice) do |form| %>
    <% if notice.errors.any? %>
      <div class="w3-panel w3-red w3-display-container">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-large w3-display-topright">&times;</span>
        <h2><%= pluralize(notice.errors.count, "error") %> prohibited this Pengumuman from being saved:</h2>

        <ul class="w3-ul w3-border-top w3-border-bottom w3-section">
          <% notice.errors.each do |error| %>
            <li><i class="fa fa-circle-o" aria-hidden="true"></i> <%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: 'w3-input' %>
    </div>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.rich_text_area :body, class: "w3-section"  %>
    </div>  

    <div>
      <%= form.submit "Submit", class: 'w3-button w3-blue'%>
    </div>
  <% end %>
<% end %>

app/views/notices/_notice.html.erb
<div id="<%= dom_id notice %>">
  <p>
    <strong>Title:</strong>
    <%= notice.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= notice.body %>
  </p>

  <p>
    <strong>Posted By:</strong>
    <%= notice.user.name %>
  </p>

</div>

app/views/notices/_notice_table.html.erb
    <tr id="<%= dom_id notice %>" is="turbo-frame">
        <td><%= notice.title %></td>
        <td><%= notice.body.to_plain_text.slice(0, 15) %></td>
        <td><%= notice.user.name %></td>
        <td>
            <div class="w3-row">
                <div class="w3-third">
                    <button class="w3-button">
                    <%= link_to notice_path(notice) do %>
                        <i class="fa fa-eye w3-text-green" aria-hidden="true"></i>
                    <% end %>
                    </button>
                </div>
                <div class="w3-third">
                    <button class="w3-button">
                    <%= link_to edit_notice_path(notice) do %>
                        <i class="fa fa-pencil-square-o w3-text-blue" aria-hidden="true"></i>
                    <% end %>
                    </button>
                </div>
                <div class="w3-third">
                    <%= button_to notice_path(notice), method: :delete, class: "destroy-button w3-button", form: { data: { turbo_confirm: "Are you sure?" } } do %>
                        <i class="fa fa-trash-o w3-text-red" aria-hidden="true"></i>
                    <% end %>
                </div>
            </div>
        </td>
    </tr>

app/views/notices/create.turbo_stream.erb
<%= turbo_stream.prepend "notices" do %>
    <%= render partial: "notice_table", locals: {notice: @notice} %>
<% end %>
<%= turbo_stream.replace "new_notice", partial: "form", locals: { notice: Notice.new } %>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render "form", notice: @notice %>

<br>

<div>
  <%= link_to "Show this notice", @notice %> |
  <%= link_to "Back to notices", notices_path %>
</div>

app/views/notices/index.html.erb
<h1>Pengumuman</h1>
<%= render 'form', notice: Notice.new %>
<div class="w3-responsive">
<table class="w3-table-all w3-section">
  <thead>
      <tr>
          <th>Title</th>
          <th>Body</th>
          <th>Posted By</th>
          <th>Action</th>
      </tr>    
  </thead>
  <tbody id="notices" is="turbo-frame">
  <% @notices.each do |notice| %>
    <%= render partial: 'notice_table', locals: {notice: notice} %>              
  <% end %>
  </tbody>
</table>
</div>
<%= paginate @notices, window: 2 %>

app/views/notices/new.html.erb
<%= render "form", notice: @notice %>

<br>

<div>
  <%= link_to "Back to notices", notices_path %>
</div>

app/views/notices/new.turbo_stream.erb
<%= turbo_stream.replace "new_notice" do %>
    <%= render partial: "form", locals: { notice: @notice } %>
<% end %>

app/views/notices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notice %>

<% if current_user == @notice.user %>
<div>
  <%= link_to "Edit this notice", edit_notice_path(@notice) %> |
  <%= link_to "Back to notices", notices_path %>

  <%= button_to "Destroy this notice", @notice, method: :delete %>
</div>
<% end %>


<div class="w3-container">  
  <%= render 'comments/form', notice: @notice, comment: @notice.comments.build, submit_label: "Reply" %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', notice: @notice, comment: comment %>
  <% end %>
</div>