config/routes.rb
Rails.application.routes.draw do
  resources :spks
  resources :master_kapals
  root 'dashboard#index'  
  authenticated :user, ->(user) { user.admin? } do    
    get 'dashboard/pelabuhans'
    get 'dashboard/notices'
    get 'dashboard/comments'
    get 'dashboard/users'
    get 'dashboard/show_notice'
    get 'dashboard/routes'
  end
  get 'search', to: "search#index"
  get 'search/pelabuhan', to: "search#pelabuhan"
  get 'search/master_kapal', to: "search#master_kapal"
  resources :pelabuhans  
  devise_for :users, skip: [:sessions], controllers: {
    session: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session    
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'register', to: 'devise/registrations#new', as: :new_user_registration_c    
  end

  resources :notices do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")  
  # root "articles#index"  
end

app/models/pelabuhan.rb
class Pelabuhan < ApplicationRecord
    belongs_to :user
    has_many :spk, foreign_key: 'pelabuhan'
    validates :daerah, presence: true
    validates :nama_pelabuhan, presence: true
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "daerah", "id", "nama_pelabuhan", "updated_at", "user_id"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["user"]
    end
end

app/controllers/pelabuhans_controller.rb
class PelabuhansController < ApplicationController
  before_action :set_pelabuhan, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /pelabuhans or /pelabuhans.json
  def index
    @pelabuhans = Pelabuhan.includes(:user).all.order(created_at: :desc).page(params[:page]).per(5)
    add_breadcrumb('Pelabuhan', nil, true)
  end

  # GET /pelabuhans/1 or /pelabuhans/1.json
  def show
    add_breadcrumb('Pelabuhan', pelabuhans_path, false)
    add_breadcrumb(@pelabuhan.daerah, nil, true)
    add_breadcrumb(@pelabuhan.nama_pelabuhan, nil, true)
  end

  # GET /pelabuhans/new
  def new
    @pelabuhan = Pelabuhan.new
  end

  # GET /pelabuhans/1/edit
  def edit
  end

  # POST /pelabuhans or /pelabuhans.json
  def create
    @pelabuhan = Pelabuhan.new(pelabuhan_params)
    @pelabuhan.user = current_user

    respond_to do |format|
      if Pelabuhan.exists?(nama_pelabuhan: @pelabuhan.nama_pelabuhan)        
        format.html { redirect_to pelabuhan_url(@pelabuhan), alert: "Pelabuhan with the same name already exists." }
        format.turbo_stream { render :new, status: :unprocessable_entity, locals: { pelabuhan: @pelabuhan } }
        format.json { render json: @pelabuhan.errors, status: :unprocessable_entity }
      elsif @pelabuhan.save
        format.html { redirect_to pelabuhan_url(@pelabuhan), notice: "Pelabuhan was successfully created." }
        format.turbo_stream { render :create, locals: {pelabuhan: @pelabuhan} }
        format.json { render :show, status: :created, location: @pelabuhan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :new, status: :unprocessable_entity, locals: {pelabuhan: @pelabuhan} }
        format.json { render json: @pelabuhan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pelabuhans/1 or /pelabuhans/1.json
  def update
    respond_to do |format|
      if @pelabuhan.update(pelabuhan_params)
        format.html { redirect_to pelabuhan_url(@pelabuhan), notice: "Pelabuhan was successfully updated." }
        format.json { render :show, status: :ok, location: @pelabuhan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pelabuhan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pelabuhans/1 or /pelabuhans/1.json
  def destroy
    @pelabuhan.destroy

    respond_to do |format|
      format.html { redirect_to pelabuhans_url, notice: "Pelabuhan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelabuhan
      @pelabuhan = Pelabuhan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pelabuhan_params
      params.require(:pelabuhan).permit(:daerah, :nama_pelabuhan,)
    end
end

app/helpers/pelabuhans_helper.rb
module PelabuhansHelper
end

app/views/pelabuhans/_form.html.erb
<%= turbo_frame_tag "new_pelabuhan" do %>
  <%= form_with(model: pelabuhan) do |form| %>
    <% if pelabuhan.errors.any? %>
      <div class="w3-panel w3-red w3-display-container">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-large w3-display-topright">&times;</span>
        <h2><%= pluralize(pelabuhan.errors.count, "error") %> prohibited this pelabuhan from being saved:</h2>

        <ul class="w3-ul w3-border-top w3-border-bottom w3-section">
          <% pelabuhan.errors.each do |error| %>
            <li><i class="fa fa-circle-o" aria-hidden="true"></i> <%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :daerah, style: "display: block" %>
      <%= form.text_field :daerah, class: 'w3-input' %>
    </div>

    <div>
      <%= form.label :nama_pelabuhan, style: "display: block" %>
      <%= form.text_field :nama_pelabuhan, class: 'w3-input' %>
    </div>

    <div class="w3-section">
      <%= form.submit "Submit", class: 'w3-button w3-blue'%>
    </div>
  <% end %>
<% end %>

app/views/pelabuhans/_pelabuhan.html.erb
<div id="<%= dom_id pelabuhan %>">
  <p>
    <strong>Daerah:</strong>
    <%= pelabuhan.daerah %>
  </p>

  <p>
    <strong>Nama pelabuhan:</strong>
    <%= pelabuhan.nama_pelabuhan %>
  </p>
  <p>
    <strong>Posted By:</strong>
    <%= pelabuhan.user.name %>
  </p>  
</div>

app/views/pelabuhans/_pelabuhan_table.html.erb
    <tr id="<%= dom_id pelabuhan %>" is="turbo-frame">
        <td><%= pelabuhan.daerah %></td>
        <td><%= pelabuhan.nama_pelabuhan %></td>
        <td><%= pelabuhan.user.name %></td>
        <td>
            <div class="w3-row">
                <div class="w3-third">
                    <button class="w3-button">
                    <%= link_to pelabuhan_path(pelabuhan) do %>
                        <i class="fa fa-eye w3-text-green" aria-hidden="true"></i>
                    <% end %>
                    </button>
                </div>
                <div class="w3-third">
                    <button class="w3-button">
                    <%= link_to edit_pelabuhan_path(pelabuhan) do %>
                        <i class="fa fa-pencil-square-o w3-text-blue" aria-hidden="true"></i>
                    <% end %>
                    </button>
                </div>
                <div class="w3-third">
                    <%= button_to pelabuhan_path(pelabuhan), method: :delete, class: "destroy-button w3-button", form: { data: { turbo_confirm: "Are you sure?" } } do %>
                        <i class="fa fa-trash-o w3-text-red" aria-hidden="true"></i>
                    <% end %>
                </div>
            </div>
        </td>
    </tr>

app/views/pelabuhans/create.turbo_stream.erb
<%= turbo_stream.prepend "pelabuhans" do %>
    <%= render partial: "pelabuhan_table", locals: {pelabuhan: @pelabuhan} %>
<% end %>
<%= turbo_stream.replace "new_pelabuhan", partial: "form", locals: { pelabuhan: Pelabuhan.new } %>

app/views/pelabuhans/edit.html.erb
<h1>Editing pelabuhan</h1>

<%= render "form", pelabuhan: @pelabuhan %>

<br>

<div>
  <%= link_to "Show this pelabuhan", @pelabuhan %> |
  <%= link_to "Back to pelabuhans", pelabuhans_path %>
</div>

app/views/pelabuhans/index.html.erb
<h1>Pelabuhans</h1>
<%= render 'search/form' %>
<%= render 'form', pelabuhan: Pelabuhan.new %>
<div class="w3-responsive">
<table class="w3-table-all w3-section">
  <thead>
      <tr>
          <th>Title</th>
          <th>Body</th>
          <th>Posted By</th>
          <th>Action</th>
      </tr>    
  </thead>
  <tbody id="pelabuhans" is="turbo-frame">
  <% @pelabuhans.each do |pelabuhan| %>
    <%= render partial: 'pelabuhan_table', locals: {pelabuhan: pelabuhan} %>              
  <% end %>
  </tbody>
</table>
</div>
<%= paginate @pelabuhans, window: 2 %>

app/views/pelabuhans/new.html.erb
<h1>New pelabuhan</h1>

<%= render "form", pelabuhan: @pelabuhan %>
<br>

<div>
  <%= link_to "Back to pelabuhans", pelabuhans_path %>
</div>

app/views/pelabuhans/new.turbo_stream.erb
<%= turbo_stream.replace "new_pelabuhan" do %>
    <%= render partial: "form", locals: { pelabuhan: @pelabuhan } %>
<% end %>

app/views/pelabuhans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pelabuhan %>

<div>
  <%= link_to "Edit this pelabuhan", edit_pelabuhan_path(@pelabuhan) %> |
  <%= link_to "Back to pelabuhans", pelabuhans_path %>

  <%= button_to "Destroy this pelabuhan", @pelabuhan, method: :delete %>
</div>