config/routes.rb
Rails.application.routes.draw do
  resources :spks
  resources :master_kapals
  root 'dashboard#index'  
  authenticated :user, ->(user) { user.admin? } do    
    get 'dashboard/pelabuhans'
    get 'dashboard/notices'
    get 'dashboard/comments'
    get 'dashboard/users'
    get 'dashboard/show_notice'
    get 'dashboard/routes'
  end
  get 'search', to: "search#index"
  get 'search/pelabuhan', to: "search#pelabuhan"
  get 'search/master_kapal', to: "search#master_kapal"
  resources :pelabuhans  
  devise_for :users, skip: [:sessions], controllers: {
    session: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session    
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'register', to: 'devise/registrations#new', as: :new_user_registration_c    
  end

  resources :notices do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")  
  # root "articles#index"  
end

app/models/master_kapal.rb
class MasterKapal < ApplicationRecord
    enum jenis_kapal: [ :MV, :MT, :TB, :TK, :PENUMPANG, :KERUK, :KHUSUS ]
    has_one_attached :surat_ukur
    has_one_attached :surat_laut
    has_one_attached :foto_kapal    
    validate :image_file_format
    has_many :spk, foreign_key: 'kapal'
    validates_presence_of :nama_kapal, :bendera, :pemilik, :alamat_owner, :jenis_pelayaran, :jenis_kapal, :imo_number, :call_sign, :dwt, :gt, :loa, :draft_depan, :draft_belakang, :hp_mesin
    def self.ransackable_attributes(auth_object = nil)
      ["alamat_owner", "bendera", "call_sign", "created_at", "draft_belakang", "draft_depan", "dwt", "gt", "hp_mesin", "id", "imo_number", "jenis_kapal", "jenis_pelayaran", "loa", "nama_kapal", "pemilik", "updated_at"]
    end
    def self.ransackable_associations(auth_object = nil)
      ["foto_kapal_attachment", "foto_kapal_blob", "spk", "surat_laut_attachment", "surat_laut_blob", "surat_ukur_attachment", "surat_ukur_blob"]
    end
    private

    def image_file_format
      return unless foto_kapal.attached?
      unless foto_kapal.content_type.in?(%w(image/jpeg image/png image/gif))
        foto_kapal.purge
        errors.add(:foto_kapal, 'must be a JPEG, PNG, or GIF image')
      end
    end

end

app/controllers/master_kapals_controller.rb
class MasterKapalsController < ApplicationController
  before_action :set_master_kapal, only: %i[ show edit update destroy ]

  # GET /master_kapals or /master_kapals.json
  def index
    @master_kapals = MasterKapal.includes(:surat_ukur_attachment, :surat_laut_attachment, :foto_kapal_attachment).all.order(created_at: :desc).page(params[:page]).per(5)
    add_breadcrumb('Master Kapal', nil, true)
  end

  # GET /master_kapals/1 or /master_kapals/1.json
  def show
  end

  # GET /master_kapals/new
  def new
    @master_kapal = MasterKapal.new
  end

  # GET /master_kapals/1/edit
  def edit
  end

  # POST /master_kapals or /master_kapals.json
  def create
    @master_kapal = MasterKapal.new(master_kapal_params)

    respond_to do |format|
      if @master_kapal.save
        format.html { redirect_to master_kapal_url(@master_kapal), notice: "Master kapal was successfully created." }
        format.json { render :show, status: :created, location: @master_kapal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @master_kapal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /master_kapals/1 or /master_kapals/1.json
  def update
    respond_to do |format|
      if @master_kapal.update(master_kapal_params)
        format.html { redirect_to master_kapal_url(@master_kapal), notice: "Master kapal was successfully updated." }
        format.json { render :show, status: :ok, location: @master_kapal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @master_kapal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_kapals/1 or /master_kapals/1.json
  def destroy
    @master_kapal.destroy

    respond_to do |format|
      format.html { redirect_to master_kapals_url, notice: "Master kapal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master_kapal
      @master_kapal = MasterKapal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def master_kapal_params
      params.require(:master_kapal).permit(:nama_kapal, :bendera, :pemilik, :alamat_owner, :jenis_pelayaran, :jenis_kapal, :imo_number, :call_sign, :dwt, :gt, :loa, :draft_depan, :draft_belakang, :hp_mesin, :surat_ukur, :surat_laut, :foto_kapal)
    end
end

app/helpers/master_kapals_helper.rb
module MasterKapalsHelper
end

app/views/master_kapals/_file_preview.html.erb
<div data-controller="previews">
    <%= form.label :foto_kapal %> <br>
    <%= form.file_field :foto_kapal,
        direct_upload: true,
        data: { previews_target: "input", action: "change->previews#preview" } %>
    <% if master_kapal.foto_kapal.attached? %>
      <%= image_tag master_kapal.foto_kapal.variant(resize_to_limit: [200, 200]), data: { previews_target: "preview" }, class: "w3-image" %>
    <% else %>
    <%= image_tag "", data: { previews_target: "preview" }, class: "w3-image" %>
    <% end %>
</div>

app/views/master_kapals/_form.html.erb
<%= form_with(model: master_kapal) do |form| %>
  <% if master_kapal.errors.any? %>
      <div class="w3-panel w3-red w3-display-container">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-large w3-display-topright">&times;</span>
        <h2><%= pluralize(master_kapal.errors.count, "error") %> prohibited this master_kapal from being saved:</h2>

        <ul class="w3-ul w3-border-top w3-border-bottom w3-section">
          <% master_kapal.errors.each do |error| %>
            <li><i class="fa fa-circle-o" aria-hidden="true"></i> <%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div>
    <%= form.label :nama_kapal, style: "display: block" %>
    <%= form.text_field :nama_kapal %>
  </div>

  <div>
    <%= form.label :bendera, style: "display: block" %>
    <%= form.text_field :bendera %>
  </div>

  <div>
    <%= form.label :pemilik, style: "display: block" %>
    <%= form.text_field :pemilik %>
  </div>

  <div>
    <%= form.label :alamat_owner, style: "display: block" %>
    <%= form.text_field :alamat_owner %>
  </div>

  <div>
    <%= form.label :jenis_pelayaran, style: "display: block" %>
    <%= form.text_field :jenis_pelayaran %>
  </div>

  <div>
  <%= form.label :jenis_kapal, style: "display: block" %>
  <%= form.select :jenis_kapal, MasterKapal.jenis_kapals.keys, {}, class: "form-control" %>
</div>


  <div>
    <%= form.label :imo_number, style: "display: block" %>
    <%= form.number_field :imo_number %>
  </div>

  <div>
    <%= form.label :call_sign, style: "display: block" %>
    <%= form.text_field :call_sign %>
  </div>

  <div>
    <%= form.label :dwt, style: "display: block" %>
    <%= form.number_field :dwt %>
  </div>

  <div>
    <%= form.label :gt, style: "display: block" %>
    <%= form.number_field :gt %>
  </div>

  <div>
    <%= form.label :loa, style: "display: block" %>
    <%= form.number_field :loa %>
  </div>

  <div>
    <%= form.label :draft_depan, style: "display: block" %>
    <%= form.number_field :draft_depan %>
  </div>

  <div>
    <%= form.label :draft_belakang, style: "display: block" %>
    <%= form.number_field :draft_belakang %>
  </div>

  <div>
    <%= form.label :hp_mesin, style: "display: block" %>
    <%= form.number_field :hp_mesin %>
  </div>
  <div>
    <strong>Surat Ukur:</strong>
    <% if master_kapal.surat_ukur.attached? %>      
      <button onclick="sanTampil('<%= master_kapal.surat_ukur %>')" class="w3-button w3-blue">Tampil</button>      
      <embed src="<%= url_for(master_kapal.surat_ukur) %>" type="application/pdf" width="500" height="600" id="<%= master_kapal.surat_ukur %>" class="w3-hide">
      <%= link_to 'Download', rails_blob_path(master_kapal.surat_ukur, disposition: 'attachment') %>
    <% else %>
      No Surat Ukur Uploaded
    <% end %>
  </div>
  <div>
    <%= form.label :surat_ukur %> <br>
    <%= form.file_field :surat_ukur %>
  </div>
  <div>
    <strong>Surat Laut:</strong>
    <% if master_kapal.surat_laut.attached? %>      
      <button onclick="sanTampil('<%= master_kapal.surat_laut %>')" class="w3-button w3-blue">Tampil</button>
      <embed src="<%= url_for(master_kapal.surat_laut) %>" type="application/pdf" width="500" height="600" id="<%= master_kapal.surat_laut %>" class="w3-hide">
      <%= link_to 'Download', rails_blob_path(master_kapal.surat_laut, disposition: 'attachment') %>
    <% else %>
      No Surat Laut Uploaded
    <% end %>
  </div>
  <div>
    <%= form.label :surat_laut %> <br>
    <%= form.file_field :surat_laut %>
  </div>
  <div>
    <strong>Foto Kapal:</strong>
    <% if master_kapal.foto_kapal.attached? %>
      <%= link_to image_tag(master_kapal.foto_kapal.variant(resize_to_limit: [200, 200])), rails_blob_path(master_kapal.foto_kapal, disposition: 'attachment') %>
    <% else %>
      No Foto Kapal Uploaded
    <% end %>
  </div>
  <%= render 'file_preview', form: form, master_kapal: master_kapal %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/master_kapals/_master_kapal.html.erb
<div id="<%= dom_id master_kapal %>">
  <p>
    <strong>Nama kapal:</strong>
    <%= master_kapal.nama_kapal %>
  </p>

  <p>
    <strong>Bendera:</strong>
    <%= master_kapal.bendera %>
  </p>

  <p>
    <strong>Pemilik:</strong>
    <%= master_kapal.pemilik %>
  </p>

  <p>
    <strong>Alamat owner:</strong>
    <%= master_kapal.alamat_owner %>
  </p>

  <p>
    <strong>Jenis pelayaran:</strong>
    <%= master_kapal.jenis_pelayaran %>
  </p>

  <p>
    <strong>Jenis kapal:</strong>
    <%= master_kapal.jenis_kapal %>
  </p>

  <p>
    <strong>Imo number:</strong>
    <%= master_kapal.imo_number %>
  </p>

  <p>
    <strong>Call sign:</strong>
    <%= master_kapal.call_sign %>
  </p>

  <p>
    <strong>Dwt:</strong>
    <%= master_kapal.dwt %>
  </p>

  <p>
    <strong>Gt:</strong>
    <%= master_kapal.gt %>
  </p>

  <p>
    <strong>Loa:</strong>
    <%= master_kapal.loa %>
  </p>

  <p>
    <strong>Draft depan:</strong>
    <%= master_kapal.draft_depan %>
  </p>

  <p>
    <strong>Draft belakang:</strong>
    <%= master_kapal.draft_belakang %>
  </p>

  <p>
    <strong>Hp mesin:</strong>
    <%= master_kapal.hp_mesin %>
  </p>
<div>
    <strong>Surat Ukur:</strong>
    <% if master_kapal.surat_ukur.attached? %>      
      <button onclick="sanTampil('<%= master_kapal.surat_ukur %>')" class="w3-button w3-blue">Tampil</button>      
      <embed src="<%= url_for(master_kapal.surat_ukur) %>" type="application/pdf" width="500" height="600" id="<%= master_kapal.surat_ukur %>" class="w3-hide">
      <%= link_to 'Download', rails_blob_path(master_kapal.surat_ukur, disposition: 'attachment') %>
    <% else %>
      No Surat Ukur Uploaded
    <% end %>
  </div>
  <div>
    <strong>Surat Laut:</strong>
    <% if master_kapal.surat_laut.attached? %>      
      <button onclick="sanTampil('<%= master_kapal.surat_laut %>')" class="w3-button w3-blue">Tampil</button>
      <embed src="<%= url_for(master_kapal.surat_laut) %>" type="application/pdf" width="500" height="600" id="<%= master_kapal.surat_laut %>" class="w3-hide">
      <%= link_to 'Download', rails_blob_path(master_kapal.surat_laut, disposition: 'attachment') %>
    <% else %>
      No Surat Laut Uploaded
    <% end %>
  </div>
  <div>
    <strong>Foto Kapal:</strong>
    <% if master_kapal.foto_kapal.attached? %>
      <%= link_to image_tag(master_kapal.foto_kapal.variant(resize_to_limit: [200, 200])), rails_blob_path(master_kapal.foto_kapal, disposition: 'attachment') %>
    <% else %>
      No Foto Kapal Uploaded
    <% end %>
  </div>
</div>

app/views/master_kapals/_master_kapal_table.html.erb
    <tr id="<%= dom_id master_kapal %>" is="turbo-frame">
        <td><%= master_kapal.nama_kapal %></td>
        <td><%= master_kapal.bendera %></td>
        <td><%= master_kapal.pemilik %></td>
        <td><%= master_kapal.alamat_owner %></td>
        <td><%= master_kapal.jenis_pelayaran %></td>
        <td><%= master_kapal.jenis_kapal %></td>
        <td><%= master_kapal.imo_number %></td>
        <td><%= master_kapal.call_sign %></td>
        <td><%= master_kapal.dwt %></td>
        <td><%= master_kapal.gt %></td>
        <td><%= master_kapal.loa %></td>
        <td><%= master_kapal.draft_depan %></td>
        <td><%= master_kapal.draft_belakang %></td>
        <td><%= master_kapal.hp_mesin %></td>
        <td>
        <% if master_kapal.surat_ukur.attached? %>              
            <%= link_to 'DL', rails_blob_path(master_kapal.surat_ukur, disposition: 'attachment') %>
        <% else %>
            No Surat Ukur Uploaded
        <% end %>
        </td>
        <td>
        <% if master_kapal.surat_laut.attached? %>                  
            <%= link_to 'DL', rails_blob_path(master_kapal.surat_laut, disposition: 'attachment') %>
        <% else %>
            No Surat Laut Uploaded
        <% end %>
        </td>
        <td>
        <% if master_kapal.foto_kapal.attached? %>
            <%= link_to image_tag(master_kapal.foto_kapal.variant(resize_to_limit: [100, 100])), rails_blob_path(master_kapal.foto_kapal, disposition: 'inline') %>
        <% else %>
            No Foto Kapal Uploaded
        <% end %>
        </td>
        <td>
            <div class="w3-row ar-tb-action">
                <div class="w3-third">
                    <button class="w3-button">
                    <%= link_to master_kapal_path(master_kapal) do %>
                        <i class="fa fa-eye w3-text-green" aria-hidden="true"></i>
                    <% end %>
                    </button>
                </div>
                <div class="w3-third">
                    <button class="w3-button">
                    <%= link_to edit_master_kapal_path(master_kapal) do %>
                        <i class="fa fa-pencil-square-o w3-text-blue" aria-hidden="true"></i>
                    <% end %>
                    </button>
                </div>
                <div class="w3-third">
                    <%= button_to master_kapal_path(master_kapal), method: :delete, class: "destroy-button w3-button" do %>
                        <i class="fa fa-trash-o w3-text-red" aria-hidden="true"></i>
                    <% end %>
                </div>
            </div>
        </td>
    </tr>

app/views/master_kapals/edit.html.erb
<h1>Editing master kapal</h1>

<%= render "form", master_kapal: @master_kapal %>

<br>

<div>
  <%= link_to "Show this master kapal", @master_kapal %> |
  <%= link_to "Back to master kapals", master_kapals_path %>
</div>

app/views/master_kapals/index.html.erb
<h1>Master kapals</h1>
<%= link_to 'Tambah Data', new_master_kapal_path, class: 'w3-button w3-blue' %>
<div id="master_kapals">
<div class="w3-responsive">
<table class="w3-table-all w3-section w3-card">
  <thead>
      <tr>
          <th>Nama Kapal</th>
          <th>Bendera</th>
          <th>Pemilik</th>
          <th>Alamat Owner</th>
          <th>Jenis Pelayaran</th>
          <th>Jenis Kapal</th>
          <th>IMO Number</th>
          <th>Call Sign</th>
          <th>DWT</th>
          <th>GT</th>
          <th>LOA</th>
          <th>Draft Depan</th>
          <th>Draft Belakang</th>
          <th>HP Mesin</th> 
          <th>Surat Ukur</th>
          <th>Surat Laut</th>
          <th>Foto Kapal</th>         
          <th>Action</th>
      </tr>    
  </thead>
  <tbody id="master_kapals" is="turbo-frame">
  <% @master_kapals.each do |master_kapal| %>
    <%= render partial: 'master_kapal_table', locals: {master_kapal: master_kapal} %>              
  <% end %>
  </tbody>
</table>
</div>
<%= paginate @master_kapals, window: 2 %>

app/views/master_kapals/new.html.erb
<h1>New master kapal</h1>

<%= render "form", master_kapal: @master_kapal %>

<br>

<div>
  <%= link_to "Back to master kapals", master_kapals_path %>
</div>

app/views/master_kapals/show.html.erb
<%= render @master_kapal %>

<div>
  <%= link_to "Edit this master kapal", edit_master_kapal_path(@master_kapal) %> |
  <%= link_to "Back to master kapals", master_kapals_path %>

  <%= button_to "Destroy this master kapal", @master_kapal, method: :delete %>
</div>