config/routes.rb
Rails.application.routes.draw do
  resources :spks
  resources :master_kapals
  root 'dashboard#index'  
  authenticated :user, ->(user) { user.admin? } do    
    get 'dashboard/pelabuhans'
    get 'dashboard/notices'
    get 'dashboard/comments'
    get 'dashboard/users'
    get 'dashboard/show_notice'
    get 'dashboard/routes'
  end
  get 'search', to: "search#index"
  get 'search/pelabuhan', to: "search#pelabuhan"
  get 'search/master_kapal', to: "search#master_kapal"
  resources :pelabuhans  
  devise_for :users, skip: [:sessions], controllers: {
    session: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session    
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'register', to: 'devise/registrations#new', as: :new_user_registration_c    
  end

  resources :notices do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")  
  # root "articles#index"  
end

app/views/layouts/_footer.html.erb
<footer class="w3-container w3-blue w3-center">    
    <p>Copyright <a href="https://andikarekatias.com" target="_blank">AR</a> <%= Time.zone.now.year %> © All rights Reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="w3-container" style="padding-top:22px">
    <h5><i class="fa fa-dashboard"></i> <a href="/" class="w3-text-blue">Dashboard </a>
      <% @breadcrumbs.each do |breadcrumb| %>
        <% if breadcrumb[:current] %>
            / <%= breadcrumb[:label] %>        
        <% else %>
            / <%= link_to breadcrumb[:label], breadcrumb[:path], class: 'w3-text-blue' %>
        <% end %>
      <% end %>
     </h5>    
</header>

app/views/layouts/_msg.html.erb
<% if notice.present? %>
<div class="w3-panel w3-green w3-round-xxlarge w3-border w3-border-green">
    <h3>Information!</h3>
    <p class="notice"><%= notice %></p>
</div>    
<% end %>
<% if alert.present? %>
<div class="w3-panel w3-red w3-round-xxlarge">
    <h3>Alert!</h3>
    <p class="alert"><%= alert %></p>
</div>
<% end %>

app/views/layouts/_notification.html.erb
<%= link_to(raw(notification.to_notification.message), notification.to_notification.url, class: 'w3-bar-item w3-button w3-border-bottom') %>

app/views/layouts/_notifications.html.erb
<% if current_user %>
<div class="w3-bar-block">
    <div class="w3-dropdown-hover w3-white">
        <a href="#" class="w3-button w3-block"><i class="fa fa-envelope"></i> <span class="w3-badge w3-green"><%= @unread.count >= 9 ? "9+" : @unread.count %></span></a>
        <div id="dashNotif" class="w3-dropdown-content w3-bar-block w3-border">
            <% @unread.each do |notification|  %>
                <%= render 'layouts/notification', notification: notification %>
            <% end %>                          
            <% if @read.count + @unread.count == 0 %>
                <p class="w3-bar-item w3-button">No notifications</p>
            <% end %>
            <% @read.each do |notification|  %>
                <%= render 'layouts/notification', notification: notification %>
            <% end %>
        </div>
    </div>
</div>
<% end %>    

app/views/layouts/_sidebar.html.erb
<!-- Top container -->
<div class="w3-bar w3-top w3-blue w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();" id="testc"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right">Logo</span>
</div>
<!-- Sidebar/menu -->
<% if current_user %>
<nav class="w3-sidebar w3-collapse w3-white" style="z-index:3;width:250px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">    
    <% if current_user.image.present? %>
    <%= image_tag(current_user.image, alt: "avatar", class: "w3-circle w3-margin-right", style: "width:46px") %>
    <% else %>
      <img src="https://www.w3schools.com/w3images/avatar3.png" alt="avatar" class="w3-circle w3-margin-right" style="width:46px">
    <% end %>      
    </div>
    <div class="w3-col s8 w3-bar">
      <span><strong><%= current_user.name %> [<%= current_user.role %>]</strong></span><br>      
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <%= link_to edit_user_registration_path, class: "w3-bar-item w3-button" do %>
        <i class="fa fa-cog"></i>
      <% end %>
    </div>
    <%= render 'layouts/notifications' %>
  </div>
  <hr>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <%= link_to root_path, class: 'w3-bar-item w3-button w3-padding' do %>
      <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
    <% end %>
    <% if current_user.admin? %>
    
      <%= link_to notices_path, class: 'w3-bar-item w3-button w3-padding' do %>
        <i class="fa-solid fa-bullhorn"></i> Pengumuman
      <% end %>    
      <%= link_to pelabuhans_path, class: 'w3-bar-item w3-button w3-padding' do %>
        <i class="fa-solid fa-anchor"></i> Pelabuhan
      <% end %>  
      <%= link_to master_kapals_path, class: 'w3-bar-item w3-button w3-padding' do %>
        <i class="fa fa-ship" aria-hidden="true"></i> Master Kapal
      <% end %>
      <%= link_to spks_path, class: 'w3-bar-item w3-button w3-padding' do %>
        <i class="fa fa-file-text-o" aria-hidden="true"></i> SPK
      <% end %>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete, class: 'w3-bar-item w3-button w3-padding', 'data-turbo-method': :delete do %>
          <i class="fa fa-sign-out" aria-hidden="true"></i>  Sing Out
    <% end %><br>
  </div>
</nav>
<% end %>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if @breadcrumbs.present? %>
      <% @breadcrumbs.each do |breadcrumb| %>
        <% if breadcrumb[:current] %>
          <title>RbSan - <%= breadcrumb[:label] %></title>      
        <% end %>
      <% end %>
    <% else %>
      <title>RbSan - Dashboard</title>
    <% end %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <script src="https://kit.fontawesome.com/543620e0a3.js" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>        
  </head>

  <body class="w3-light-grey">    
    <%= render 'layouts/sidebar' %>                   
    <main class="w3-main ar-m-bottom" style="margin-left:250px;margin-top:43px;">    
    <%= render 'layouts/msg' %>
    <%= render 'layouts/header' %>
    <div class="w3-container">
      <%= yield %>
    </div>    
    <%= render 'layouts/footer' %>
    </main>    
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RbSan - Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <script src="https://kit.fontawesome.com/543620e0a3.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    <style>
    body, html {height: 100%}
    </style>
  </head>
  <body>          
      <%= yield %>          
  </body>
</html>